#include "./modules/Players/multi-account/logintxd.pwn"
// character
#include "./modules/Players/characters/Core/character.pwn"
#include "./modules/Players/characters/Core/Register/build.pwn"
#include "./modules/Players/characters/Core/_func.pwn"
#include "./modules/Players/characters/Core/_callback.pwn"
#include "./modules/Players/characters/Core/sql.pwn"
#include "./modules/Players/characters/Core/character-select-textdraw.pwn"
#include "./modules/Players/characters/Admin/character-admin.pwn"
// Spawn player
#include "./modules/Players/characters/Player/SpawnPlayer/callback.pwn"
#include "./modules/Players/characters/Player/SpawnPlayer/func.pwn"
#include "./modules/Players/characters/Player/SpawnPlayer/textdraw.pwn"
// #include "./modules/Players/characters/Player/Inventory/Inventory_Main.pwn"
#include "./modules/Players/characters/Inventory/build.pwn"