#include <VehiclePartPosition>
#include <core>
#include <float>
#include "./modules/Dev/Job/Mechanic/_var.pwn"
#include "./modules/Dev/Job/Mechanic/_include.pwn"
#include "./modules/Dev/Job/Mechanic/_callback.pwn"
#include "./modules/Dev/Job/Mechanic/_function.pwn"
#include "./modules/Dev/Job/Mechanic/_textdraw.pwn"
#include "./modules/Dev/Job/Mechanic/_cmd.pwn"