func:OnPlayerLoadEclectricianTextdraw(playerid){
    ElectricianTD[playerid][0] = CreatePlayerTextDraw(playerid, 190.000000, 143.000000, "mdl-2025:electrician");
    PlayerTextDrawFont(playerid, ElectricianTD[playerid][0], 4);
    PlayerTextDrawLetterSize(playerid, ElectricianTD[playerid][0], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, ElectricianTD[playerid][0], 249.500000, 186.500000);
    PlayerTextDrawSetOutline(playerid, ElectricianTD[playerid][0], 1);
    PlayerTextDrawSetShadow(playerid, ElectricianTD[playerid][0], 0);
    PlayerTextDrawAlignment(playerid, ElectricianTD[playerid][0], 1);
    PlayerTextDrawColour(playerid, ElectricianTD[playerid][0], -1);
    PlayerTextDrawBackgroundColour(playerid, ElectricianTD[playerid][0], 255);
    PlayerTextDrawBoxColour(playerid, ElectricianTD[playerid][0], 50);
    PlayerTextDrawUseBox(playerid, ElectricianTD[playerid][0], 1);
    PlayerTextDrawSetProportional(playerid, ElectricianTD[playerid][0], 1);
    PlayerTextDrawSetSelectable(playerid, ElectricianTD[playerid][0], 0);

    ElectricianTD[playerid][1] = CreatePlayerTextDraw(playerid, 250.000000, 245.000000, "0");
    PlayerTextDrawFont(playerid, ElectricianTD[playerid][1], 3);
    PlayerTextDrawLetterSize(playerid, ElectricianTD[playerid][1], 1.104166, 5.099998);
    PlayerTextDrawTextSize(playerid, ElectricianTD[playerid][1], 273.000000, 54.500000);
    PlayerTextDrawSetOutline(playerid, ElectricianTD[playerid][1], 0);
    PlayerTextDrawSetShadow(playerid, ElectricianTD[playerid][1], 0);
    PlayerTextDrawAlignment(playerid, ElectricianTD[playerid][1], 1);
    PlayerTextDrawColour(playerid, ElectricianTD[playerid][1], -1);
    PlayerTextDrawBackgroundColour(playerid, ElectricianTD[playerid][1], 255);
    PlayerTextDrawBoxColour(playerid, ElectricianTD[playerid][1], 50);
    PlayerTextDrawUseBox(playerid, ElectricianTD[playerid][1], 0);
    PlayerTextDrawSetProportional(playerid, ElectricianTD[playerid][1], 1);
    PlayerTextDrawSetSelectable(playerid, ElectricianTD[playerid][1], 1);

    ElectricianTD[playerid][2] = CreatePlayerTextDraw(playerid, 285.000000, 245.000000, "0");
    PlayerTextDrawFont(playerid, ElectricianTD[playerid][2], 3);
    PlayerTextDrawLetterSize(playerid, ElectricianTD[playerid][2], 1.104166, 5.099998);
    PlayerTextDrawTextSize(playerid, ElectricianTD[playerid][2], 308.500000, 54.500000);
    PlayerTextDrawSetOutline(playerid, ElectricianTD[playerid][2], 0);
    PlayerTextDrawSetShadow(playerid, ElectricianTD[playerid][2], 0);
    PlayerTextDrawAlignment(playerid, ElectricianTD[playerid][2], 1);
    PlayerTextDrawColour(playerid, ElectricianTD[playerid][2], -1);
    PlayerTextDrawBackgroundColour(playerid, ElectricianTD[playerid][2], 255);
    PlayerTextDrawBoxColour(playerid, ElectricianTD[playerid][2], 50);
    PlayerTextDrawUseBox(playerid, ElectricianTD[playerid][2], 0);
    PlayerTextDrawSetProportional(playerid, ElectricianTD[playerid][2], 1);
    PlayerTextDrawSetSelectable(playerid, ElectricianTD[playerid][2], 1);

    ElectricianTD[playerid][3] = CreatePlayerTextDraw(playerid, 322.000000, 245.000000, "0");
    PlayerTextDrawFont(playerid, ElectricianTD[playerid][3], 3);
    PlayerTextDrawLetterSize(playerid, ElectricianTD[playerid][3], 1.104166, 5.099998);
    PlayerTextDrawTextSize(playerid, ElectricianTD[playerid][3], 345.500000, 54.500000);
    PlayerTextDrawSetOutline(playerid, ElectricianTD[playerid][3], 0);
    PlayerTextDrawSetShadow(playerid, ElectricianTD[playerid][3], 0);
    PlayerTextDrawAlignment(playerid, ElectricianTD[playerid][3], 1);
    PlayerTextDrawColour(playerid, ElectricianTD[playerid][3], -1);
    PlayerTextDrawBackgroundColour(playerid, ElectricianTD[playerid][3], 255);
    PlayerTextDrawBoxColour(playerid, ElectricianTD[playerid][3], 50);
    PlayerTextDrawUseBox(playerid, ElectricianTD[playerid][3], 0);
    PlayerTextDrawSetProportional(playerid, ElectricianTD[playerid][3], 1);
    PlayerTextDrawSetSelectable(playerid, ElectricianTD[playerid][3], 1);

    ElectricianTD[playerid][4] = CreatePlayerTextDraw(playerid, 358.000000, 245.000000, "0");
    PlayerTextDrawFont(playerid, ElectricianTD[playerid][4], 3);
    PlayerTextDrawLetterSize(playerid, ElectricianTD[playerid][4], 1.104166, 5.099998);
    PlayerTextDrawTextSize(playerid, ElectricianTD[playerid][4], 380.500000, 54.500000);
    PlayerTextDrawSetOutline(playerid, ElectricianTD[playerid][4], 0);
    PlayerTextDrawSetShadow(playerid, ElectricianTD[playerid][4], 0);
    PlayerTextDrawAlignment(playerid, ElectricianTD[playerid][4], 1);
    PlayerTextDrawColour(playerid, ElectricianTD[playerid][4], -1);
    PlayerTextDrawBackgroundColour(playerid, ElectricianTD[playerid][4], 255);
    PlayerTextDrawBoxColour(playerid, ElectricianTD[playerid][4], 50);
    PlayerTextDrawUseBox(playerid, ElectricianTD[playerid][4], 0);
    PlayerTextDrawSetProportional(playerid, ElectricianTD[playerid][4], 1);
    PlayerTextDrawSetSelectable(playerid, ElectricianTD[playerid][4], 1);

    ElectricianTD[playerid][5] = CreatePlayerTextDraw(playerid, 227.000000, 193.000000, "0000");
    PlayerTextDrawFont(playerid, ElectricianTD[playerid][5], 3);
    PlayerTextDrawLetterSize(playerid, ElectricianTD[playerid][5], 0.470831, 2.049994);
    PlayerTextDrawTextSize(playerid, ElectricianTD[playerid][5], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, ElectricianTD[playerid][5], 0);
    PlayerTextDrawSetShadow(playerid, ElectricianTD[playerid][5], 0);
    PlayerTextDrawAlignment(playerid, ElectricianTD[playerid][5], 1);
    PlayerTextDrawColour(playerid, ElectricianTD[playerid][5], -1);
    PlayerTextDrawBackgroundColour(playerid, ElectricianTD[playerid][5], 255);
    PlayerTextDrawBoxColour(playerid, ElectricianTD[playerid][5], 50);
    PlayerTextDrawUseBox(playerid, ElectricianTD[playerid][5], 0);
    PlayerTextDrawSetProportional(playerid, ElectricianTD[playerid][5], 1);
    PlayerTextDrawSetSelectable(playerid, ElectricianTD[playerid][5], 0);

    ElectricianTD[playerid][6] = CreatePlayerTextDraw(playerid, 363.000000, 193.000000, "0000");
    PlayerTextDrawFont(playerid, ElectricianTD[playerid][6], 3);
    PlayerTextDrawLetterSize(playerid, ElectricianTD[playerid][6], 0.470831, 2.049994);
    PlayerTextDrawTextSize(playerid, ElectricianTD[playerid][6], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, ElectricianTD[playerid][6], 0);
    PlayerTextDrawSetShadow(playerid, ElectricianTD[playerid][6], 0);
    PlayerTextDrawAlignment(playerid, ElectricianTD[playerid][6], 1);
    PlayerTextDrawColour(playerid, ElectricianTD[playerid][6], -1);
    PlayerTextDrawBackgroundColour(playerid, ElectricianTD[playerid][6], 255);
    PlayerTextDrawBoxColour(playerid, ElectricianTD[playerid][6], 50);
    PlayerTextDrawUseBox(playerid, ElectricianTD[playerid][6], 0);
    PlayerTextDrawSetProportional(playerid, ElectricianTD[playerid][6], 1);
    PlayerTextDrawSetSelectable(playerid, ElectricianTD[playerid][6], 0);
    return 1;
}